### ISSUE TITLE
Lun file does not exist

### ISSUE THREAD

**Issue by chankruze** [N00bTree/android_device_realme_charlie#3]
```
I:Lun file '/sys/class/android_usb/android0/f_mass_storage/lun0/file' does not exist, USB storage mode disabled
```

Some user having rooted device needs to check this manually.

**Comment by fernandje06** [comment]
u can help me fix pbrp stuck on logo pbrp? firmware stock 14

**Comment by chankruze** [comment]
> u can help me fix pbrp stuck on logo pbrp? firmware stock 14

Reflash stock boot and recovery, then flash again, this is due to messed boot image. And also ask users in realme global group
